#
# Copyright (c) 2006-2019 TomAPU tomapufckgml@gmail.com
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        custom_script:
            enable: true
            category: ["Browser", "Hooked Domain"]
            name: "Execute custom script"
            description: "Execute custom script on hooked browser"
            authors: ["TomAPU"]
            target:
                user_notify: ["All"]
